import type { Metadata } from "next";
import Link from "next/link"; // Import Link
import "./globals.css";

export const metadata: Metadata = {
  title: "Favorite NPM Packages App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <nav className="bg-gray-800 text-white p-4 flex justify-between">
          {/* Use Link component for navigation */}
          <Link href="/" className="text-lg font-bold">
            Home
          </Link>
          <Link href="/favorites" className="text-lg font-bold">
            Favorites
          </Link>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
