import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body>
      <nav className="bg-gray-800 text-white p-4 flex justify-between">
        <a href="/" className="text-lg font-bold">
          Home
        </a>
        <a href="/favorites" className="text-lg font-bold">
          Favorites
        </a>
      </nav>
      <main>{children}</main>
    </body>
  </html>
  );
}
